on: [push]

jobs:
  build_godot_windows:
    runs-on: ubuntu-latest
    name: Build for Windows
    steps:
      - uses: actions/checkout@v1
      - name: Hello world action step
        id: build_win
        uses: bbrieber/godot_ci_image@latest
        with:
          build-config: 'WindowsDesktop'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: export/windows
